### ISSUE TITLE
DynaLoader error on attempts to use OpenGL::GLUT

### ISSUE THREAD

**Issue by devel-chm** [Perl-GPU/OpenGL-GLUT#1]
This is trimmed down code from release 0.70 of OpenGL.  It was working fine until I tried to change the name of the module from OpenGL to OpenGL::Modern.  Now something is failing in the load and I'm not enough of an XS guru to sort this out.

>  make test 
> Running Mkbootstrap for OpenGL::GLUT ()
> chmod 644 "GLUT.bs"
> PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
> t/00_require.t .. 1/1 
> \#   Failed test 'require OpenGL::GLUT;'
> \#   at t/00_require.t line 3.
> \#     Tried to require 'OpenGL::GLUT'.
> \#     Error:  Invalid version format (non-numeric data) at /usr/lib/perl5/5.22/x86_64-cygwin-threads/DynaLoader.pm line 216.
> \# Compilation failed in require at (eval 4) line 2.
> \# Looks like you failed 1 test of 1.
> t/00_require.t .. Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/1 subtests 
> t/01_use.t ...... 1/1 
> \#   Failed test 'use OpenGL::GLUT;'
> \#   at t/01_use.t line 3.
> \#     Tried to use 'OpenGL::GLUT'.
> \#     Error:  Invalid version format (non-numeric data) at /usr/lib/perl5/5.22/x86_64-cygwin-threads/DynaLoader.pm line 216.
> \# Compilation failed in require at t/01_use.t line 3.
> \# BEGIN failed--compilation aborted at t/01_use.t line 3.
> \# Looks like you failed 1 test of 1.
> t/01_use.t ...... Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/1 subtests 
> 
> Test Summary Report
> \-------------------
> t/00_require.t (Wstat: 256 Tests: 1 Failed: 1)
>   Failed test:  1
>   Non-zero exit status: 1
> t/01_use.t    (Wstat: 256 Tests: 1 Failed: 1)
>   Failed test:  1
>   Non-zero exit status: 1
> Files=2, Tests=2,  1 wallclock secs ( 0.03 usr  0.02 sys +  0.11 cusr  0.08 csys =  0.23 CPU)
> Result: FAIL
> Failed 2/2 test programs. 2/2 subtests failed.
> make: *** [Makefile:1046: test_dynamic] Error 1

**Comment by sisyphus** [comment]
Only way I can get it to work is to remove XSLoader. Attached patch works for me:
[diff.txt](https://github.com/devel-chm/OpenGL-GLUT/files/803474/diff.txt)

I've not used XSLoader before. The docs seem straightforward enough, but I couldn't get it to work with GLUT.pm

Cheers,
Rob

**Comment by devel-chm** [comment]
Thanks.  Now tests pass.
